
const channels = [
    {channel_name : 'general',
     message  : [
                    {sender : 'Sarah',
                     date : "2016-07-30 21:24:37",
                     the_message : 'a fake generated message',
                     id : 0,
                    },
                    {sender : 'Dave',
                     date : "2016-07-30 21:24:37",
                     the_message : 'a fake generated message',
                     id : 1,
                    },
                    {sender : 'Pam',
                     date : "2016-07-30 21:24:37",
                     the_message : 'a fake generated message',
                     id : 2,
                    },
                ],
        id : 1,
    },
    {channel_name : 'help',
     message  : [
                    {sender : 'Sarah',
                    date : "2016-07-30 21:24:37",
                    the_message : 'a fake generated message for help',
                    id : 0,
                    }
                ],
        id : 2,
        },
    {channel_name : 'react',
     message  : [
                   {sender : 'Sarah',
                   date : "2016-07-30 21:24:37",
                   the_message : 'a fake generated message for react',
                   id : 0,
                   }
               ],
    id : 3,
        },
    {channel_name : 'redux',
     message  : [
                   {sender : 'Sarah',
                   date : "2016-07-30 21:24:37",
                   the_message : 'a fake generated message for redux',
                   id : 0,
                   }
               ],
    id : 4,
     
    },
    {channel_name : 'webpack',
     message  : [
                   {sender : 'Sarah',
                   date : "2016-07-30 21:24:37",
                   the_message : 'a fake generated message for webpack',
                   id : 0,
                   }
               ],
    id : 5,
            },
    {channel_name : 'react-router',
     message  : [
                   {sender : 'Sarah',
                   date : "2016-07-30 21:24:37",
                   the_message : 'a fake generated message for react-router',
                   id : 0,
                   }
               ],
    id : 6,
            },
]



const people = [
    {name : 'Dave',
    message  : [
        {sender : 'Dave',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 0,
        },
        {sender : 'Dave',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 1,
        },
        {sender : 'Dave',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 2,
        },
    ],
    id : 1,},
    {name : 'Sarah',
    message  : [
        {sender : 'Sarah',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 0,
        },
        {sender : 'Sarah',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 1,
        },
        {sender : 'Sarah',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 2,
        },
    ],
    id : 2,},
    {name : 'Zack',
    message  : [
        {sender : 'Zack',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 0,
        },
        {sender : 'Zack',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 1,
        },
        {sender : 'Zack',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 2,
        },
    ],
    id : 3,},
    {name : 'Pam',
    message  : [
        {sender : 'Pam',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 0,
        },
        {sender : 'Pam',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 1,
        },
        {sender : 'Pam',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 2,
        },
    ],
    id : 4,},
    {name : 'Erin',
    message  : [
        {sender : 'Erin',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 0,
        },
        {sender : 'Erin',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 1,
        },
        {sender : 'Erin',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 2,
        },
    ],
    id : 5,},
    {name : 'Joe',
    message  : [
        {sender : 'Joe',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 0,
        },
        {sender : 'Joe',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 1,
        },
        {sender : 'Joe',
         date : "2016-07-30 21:24:37",
         the_message : 'a fake generated message',
         id : 2,
        },
    ],
    id : 6,},
]

export {channels};
export  {people};